export const otherGames = [
  "Street Fighter II: Championship Edition",
  "Street Fighter II: Turbo",
  "Super Street Fighter II: Turbo",
  "Super Street Fighter II Turbo HD Remix",
  "Persona 4 Golden",
  "Shin Megami Tensei: Persona 4",
  "Persona 5 Royal",
  "Ultra Street Fighter IV",
  "Super Street Fighter IV",
  "FTL: Advanced Edition",
  "Rez Infinite",
  "Rez HD",
  "Pac-Man: Championship Edition DX",
  "Mario Kart 8 Deluxe",
  "NBA Jam: Tournament Edition",
  "Halo: Combat Evolved Anniversary",
  "Ninja Gaiden Black",
  "NFL 2K5",
  "Planescape Torment Enhanced Edition",
  "Dark Souls (Remastered)",
  "Shadow of the Colossus (Remaster)",
  "The Legend of Zelda: Twilight Princess HD",
  "Day of the Tentacle (Remastered)",
  "The Elder Scrolls V: Skyrim - Special Edition",
  "Monster Hunter 4 Ultimate",
  "Tony Hawk's Pro Skater 1 + 2",
  "Demon's Souls (2020)",
  "Virtua Fighter 5: Final Showdown",
  "Outrun 2",
  "Street Fighter III: Third Strike",
  "Shin Megami Tensei: Persona 3",
  "Super Mario Advance 4: Super Mario Bros. 3",
  "Disgaea: Afternoon of Darkness",
  "The Legend of Zelda: Majora's Mask 3D",
  "Monster Hunter Tri G",
  "Dark Souls II: Scholar of the First Sin",
  "The Legend of Zelda: The Wind Waker HD",
  "Virtua Fighter 4: Evolution",
];
